[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aegis = "ELZJMHYE2ZKT5uzTa3VR9uSAkt2vwLRtsJZjFKBMjLJA"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
