[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aegis = "8dEjTZ3pzqTvBDyJdgmYQja8danJh5Mv1A886vaYQqVB"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
